[project]
base_dir = "."           # base directory to operate in (for monorepos)
src_dir = "./src"        # source directory (under the base directory) from which context will be retrieved

[run]
build = "npm run build"
test = "npm run test"
lint = "quick-lint-js"

[gptengineer-app]
project_id = "ef1c1d86-66ad-4de6-b382-984d0199719a"
openapi = []
